//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBaseItems
    {
        public long ID { get; set; }
        public string BaseItemCode { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string BaseItemTitle { get; set; }
        public string BaseItemTitleDescription { get; set; }
        public string BaseItemDescription { get; set; }
        public string BaseItemSubDescription { get; set; }
        public string BaseItemAttributes { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public Nullable<int> LanguageId { get; set; }
    
        public virtual tMenuItemCategory tMenuItemCategory { get; set; }
        public virtual tClass tClass { get; set; }
        public virtual tMenuLanguage tMenuLanguage { get; set; }
        public virtual tMenuType tMenuType { get; set; }
    }
}
