//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tClass()
        {
            this.tApprovers = new HashSet<tApprovers>();
            this.tBaseItems = new HashSet<tBaseItems>();
            this.tClassMenuTypeMap = new HashSet<tClassMenuTypeMap>();
        }
    
        public int ID { get; set; }
        public string FlightClass { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> ApproverID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tApprovers> tApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBaseItems> tBaseItems { get; set; }
        public virtual tUsers tUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tClassMenuTypeMap> tClassMenuTypeMap { get; set; }
    }
}
