//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCycle_audit
    {
        public long CycleID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public string Year { get; set; }
        public string CycleName { get; set; }
        public string CycleShortName { get; set; }
        public Nullable<int> KeyFieldID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Archived { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    }
}
