//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInstances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tInstances()
        {
            this.tCycle = new HashSet<tCycle>();
        }
    
        public int InstanceID { get; set; }
        public string Name { get; set; }
        public string Domain { get; set; }
        public string CHILIEnvironment { get; set; }
        public string CHILIWorkspaceID { get; set; }
        public string CHILIViewPrefsID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCycle> tCycle { get; set; }
    }
}
