//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLiveOrders_audit
    {
        public long LiveOrderId { get; set; }
        public string LotNo { get; set; }
        public Nullable<long> CycleId { get; set; }
        public Nullable<bool> IsConvertedToOrder { get; set; }
    }
}
