//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLiveOrderDetails
    {
        public long ID { get; set; }
        public Nullable<long> LiveOrderId { get; set; }
        public Nullable<long> MenuId { get; set; }
        public Nullable<long> RouteId { get; set; }
        public string FlightNo { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual tLiveOrders tLiveOrders { get; set; }
        public virtual tMenu tMenu { get; set; }
        public virtual tRouteDetails tRouteDetails { get; set; }
    }
}
