//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMealAllergen
    {
        public long ID { get; set; }
        public string MealName { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string GGMealName { get; set; }
        public string NO_DECLARABLE_ALLERGENS__EU_ { get; set; }
        public string PLEASE_REFER_TO_PACKAGING { get; set; }
        public string ALCOHOL { get; set; }
        public string CELERY { get; set; }
        public string CRUSTACEANS { get; set; }
        public string EGG { get; set; }
        public string FISH { get; set; }
        public string GLUTEN { get; set; }
        public string LUPINES { get; set; }
        public string MILK { get; set; }
        public string MOLLUSCS { get; set; }
        public string MUSTARD { get; set; }
        public string NUTS { get; set; }
        public string PEANUTS { get; set; }
        public string SESAME { get; set; }
        public string SOY { get; set; }
        public string SULPHITES { get; set; }
    }
}
