//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMenuForRoute
    {
        public long ID { get; set; }
        public Nullable<long> MenuID { get; set; }
        public Nullable<long> RouteID { get; set; }
        public string Flights { get; set; }
    
        public virtual tMenu tMenu { get; set; }
        public virtual tRouteDetails tRouteDetails { get; set; }
    }
}
