//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMenu()
        {
            this.tLiveOrderDetails = new HashSet<tLiveOrderDetails>();
            this.tMenuHistory = new HashSet<tMenuHistory>();
            this.tMenuApprovalStage = new HashSet<tMenuApprovalStage>();
            this.tMenuForRoute = new HashSet<tMenuForRoute>();
            this.tMenuItem = new HashSet<tMenuItem>();
            this.tMenuTemplates = new HashSet<tMenuTemplates>();
            this.tPDFGenerationTasks = new HashSet<tPDFGenerationTasks>();
        }
    
        public long ID { get; set; }
        public string MenuName { get; set; }
        public string MenuCode { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public string ChiliPDFName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<long> CycleID { get; set; }
        public Nullable<int> CurrentApprovalStatusID { get; set; }
        public Nullable<bool> IsMovedToLiveOrder { get; set; }
        public Nullable<int> ReorderCount { get; set; }
    
        public virtual tApprovalStatuses tApprovalStatuses { get; set; }
        public virtual tCycle tCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLiveOrderDetails> tLiveOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMenuHistory> tMenuHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMenuApprovalStage> tMenuApprovalStage { get; set; }
        public virtual tMenuLanguage tMenuLanguage { get; set; }
        public virtual tMenuType tMenuType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMenuForRoute> tMenuForRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMenuItem> tMenuItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMenuTemplates> tMenuTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPDFGenerationTasks> tPDFGenerationTasks { get; set; }
    }
}
