//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMenuHistory_audit
    {
        public long ID { get; set; }
        public long MenuID { get; set; }
        public Nullable<int> ActionByUserID { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    }
}
