//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNotification
    {
        public long ID { get; set; }
        public string FromUser { get; set; }
        public string SentToUser { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string NotificationMessage { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
