//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrders()
        {
            this.tBoxTicketData = new HashSet<tBoxTicketData>();
        }
    
        public long OrderID { get; set; }
        public Nullable<long> LiveOrderId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> OrderCycleStartDate { get; set; }
        public Nullable<System.DateTime> OrderCycleEndDate { get; set; }
        public string OrderFriendlyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBoxTicketData> tBoxTicketData { get; set; }
        public virtual tLiveOrders tLiveOrders { get; set; }
        public virtual tOrderStatus tOrderStatus { get; set; }
    }
}
