//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPDFGenerationTasksPackingTicket
    {
        public long ID { get; set; }
        public long BoxTicketID { get; set; }
        public int PackingTemplateID { get; set; }
        public int PDFGenerationJobID { get; set; }
        public string Status { get; set; }
        public string ChiliDocumentID { get; set; }
        public string ChiliTaskID { get; set; }
        public string ChiliPDFURL { get; set; }
        public string ChiliError { get; set; }
        public string LocalPDFFile { get; set; }
        public int MergeQuantity { get; set; }
    
        public virtual tBoxTicketData tBoxTicketData { get; set; }
        public virtual tPDFGenerationJobs tPDFGenerationJobs { get; set; }
    }
}
