//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSchedules
    {
        public int ID { get; set; }
        public string Subject { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string UserID { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> RecurrenceParentID { get; set; }
        public string Annotations { get; set; }
        public string Description { get; set; }
        public string Remainder { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> ColorID { get; set; }
    
        public virtual tSchedulerColors tSchedulerColors { get; set; }
    }
}
