//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSeatConfiguration
    {
        public int ID { get; set; }
        public string Registration { get; set; }
        public string GMtype { get; set; }
        public string TypeAndSeries { get; set; }
        public string Equipment { get; set; }
        public string AircraftName { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> UC { get; set; }
        public Nullable<int> PE { get; set; }
        public Nullable<int> Eco { get; set; }
    }
}
