//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTemplates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTemplates()
        {
            this.tMenuTemplates = new HashSet<tMenuTemplates>();
            this.tPDFGenerationTasks = new HashSet<tPDFGenerationTasks>();
        }
    
        public int TemplateID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public string ChiliDocumentID { get; set; }
        public string Version { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string TemplateDescription { get; set; }
    
        public virtual tMenuLanguage tMenuLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMenuTemplates> tMenuTemplates { get; set; }
        public virtual tMenuType tMenuType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPDFGenerationTasks> tPDFGenerationTasks { get; set; }
    }
}
