//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserPermissions
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> CanImport { get; set; }
        public Nullable<bool> CanExport { get; set; }
        public Nullable<bool> CanCreateCampaign { get; set; }
        public Nullable<bool> CanDeleteCampaign { get; set; }
        public Nullable<bool> CanViewPricing { get; set; }
        public Nullable<bool> IsSuper { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
    
        public virtual tUsers tUsers { get; set; }
    }
}
