//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVirginGGMapping
    {
        public long ID { get; set; }
        public string VirginMealName { get; set; }
        public string GGAllergenName { get; set; }
        public string GGNutritionalGuideName { get; set; }
        public string Pre_select_Code { get; set; }
        public string Meal_Sequence { get; set; }
        public string ShortMealName { get; set; }
        public string SubCategory { get; set; }
    }
}
