//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVirginNutritionalGuide
    {
        public long ID { get; set; }
        public string GGMealName { get; set; }
        public string Weight__Serving { get; set; }
        public string Energy_kcal_kJ_per_serving { get; set; }
        public string Fat_g_portion { get; set; }
        public string Fat___of_an_adult_s_reference_intake { get; set; }
        public string Saturated_g_portion { get; set; }
        public string Saturated___of_an_adults_reference_intake { get; set; }
        public string Sugars_g_portion { get; set; }
        public string Sugars___of_an_adult_s_reference_intake { get; set; }
        public string Fibre__g_ { get; set; }
        public string Protein__g_ { get; set; }
        public string Salt_g_portion { get; set; }
        public string Salt___of_an_adult_s_reference_intake { get; set; }
        public string kcal_kJ_per_100g { get; set; }
        public string Origin { get; set; }
        public string Pre_select_Code { get; set; }
    }
}
