//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVirginEcommerceFixedItems_AUDIT
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string SubCategory2 { get; set; }
        public Nullable<bool> Vegitarian { get; set; }
        public Nullable<bool> GlutenFree { get; set; }
        public Nullable<bool> DiaryFree { get; set; }
        public Nullable<bool> Vegan { get; set; }
        public Nullable<bool> CelebrityChef { get; set; }
        public Nullable<bool> MixerAvailable { get; set; }
        public Nullable<bool> IsMixer { get; set; }
        public string AddOnDescription1 { get; set; }
        public Nullable<bool> AddOnDefaultOn1 { get; set; }
        public string AddOnDescription2 { get; set; }
        public Nullable<bool> AddOnDefaultOn2 { get; set; }
        public string AddOnDescription3 { get; set; }
        public Nullable<bool> AddOnDefaultOn3 { get; set; }
        public string SpecificationDescription1 { get; set; }
        public string SpecificationValue1 { get; set; }
        public string SpecificationDescription2 { get; set; }
        public string SpecificationValue2 { get; set; }
        public string SpecificationDescription3 { get; set; }
        public string SpecificationValue3 { get; set; }
        public string SpecificationDescription4 { get; set; }
        public string SpecificationValue4 { get; set; }
        public string FlightNo { get; set; }
        public Nullable<long> CycleId { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> DeletedItemExtracted { get; set; }
        public Nullable<System.DateTime> DeletedItemExtractedOn { get; set; }
        public string NewOrAmend { get; set; }
        public Nullable<bool> IsAvailableInLoft { get; set; }
    }
}
