//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVirginMenuExtractFixedItems
    {
        public long ID { get; set; }
        public string ProductType { get; set; }
        public string PageHeader { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string CateogryTitle { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public string ItemSubDescription { get; set; }
    }
}
